apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: sysdigcloud
    role: rsyslog-ef
  name: rsyslog-ef
spec:
  ports:
  - name: tcp
    port: 514
    protocol: TCP
    targetPort: 514
  selector:
    app: rsyslog-ef
  sessionAffinity: None
  type: ClusterIP
